spack:
  definitions:
  - pkgs:
    - flecsalemm-deps+hdf5+caliper+doxygen+graphviz+trilinos
    - flecsi-sp+external_cinch+hdf5+caliper+doxygen+graphviz+portage
    - flecsi+external_cinch+hdf5 caliper_detail=medium +doxygen+graphviz
  - compilers:
    - '%gcc@7.4.0'
    - '%gcc@8.3.0'
  - backends:
    - backend=mpi
    - backend=legion
    - backend=hpx ^boost@1.71.0
  - mpi_providers:
    - mpich@3.2.1+slurm+verbs
    - openmpi@3.1.4 fabrics=auto
  specs:
  - flecsi@2.1.0~external_cinch ^openmpi@4.1.0
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$backends]
    - [$^mpi_providers]
  - matrix:
    - [libristra+paraview]
    - [$compilers]
    - [$^mpi_providers]
  packages:
    all:
      target: [x86_64]
      version: []
      compiler: []
      buildable: true
      providers: {}
  view: false
