spack:
  definitions:
  - pkgs:
    - flecsalemm-deps+hdf5+caliper+doxygen+graphviz+trilinos  ^flecsi+doxygen+graphviz ^flecsi-sp+doxygen+graphviz ^caliper~libdw
    - flecsi-sp+external_cinch+hdf5+caliper+doxygen+graphviz+portage ^flecsi+doxygen+graphviz ^caliper~libdw
    - flecsi+external_cinch+hdf5 caliper_detail=medium +doxygen+graphviz ^caliper@2.0.1~adiak~libdw ^hdf5+hl
  - compilers:
    - '%gcc@7.4.0'
    - '%gcc@8.3.0'
  - backends:
    - backend=mpi
    - backend=legion
    - backend=hpx
  - mpi_providers:
    - mpich@3.2.1+slurm+verbs
    - openmpi@3.1.4 fabrics=auto
  specs:
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$backends]
    - [$^mpi_providers]
  - matrix:
    - [libristra+paraview]
    - [$compilers]
    - [$^mpi_providers]
  packages:
    all:
      target: [x86_64]
      version: []
      compiler: []
      buildable: true
      modules: {}
      providers: {}
      paths: {}
  view: false
