spack:
  definitions:
  - pkgs:
    - flecsalemm-deps+hdf5+caliper+doxygen+graphviz+trilinos
  - compilers:
    - '%gcc@7.4.0'
  - backends:
    - backend=mpi
  - mpi_providers:
    - mpich@3.2.1+slurm
  specs:
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$backends]
    - [$^mpi_providers]
  packages:
    all:
      target: [x86_64]
      version: []
      compiler: []
      buildable: true
      modules: {}
      providers: {}
      paths: {}
  view: false
