spack:
  definitions:
  - pkgs:
    - flecsalemm-deps+hdf5+caliper+doxygen+graphviz
  - compilers:
    - '%gcc@7.4.0'
  - backends:
    - backend=mpi
  - mpi_providers:
    - mpich@3.2.1+slurm+verbs device=ch3
  specs:
  - flecsi@2.1.0~external_cinch+hdf5 caliper_detail=low %gcc@9.3.0 ^mpich@3.4.1+slurm+verbs device=ch3
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$backends]
    - [$^mpi_providers]
  packages:
    all:
      target: [x86_64]
      version: []
      compiler: []
      buildable: true
      providers: {}
  view: false
