spack:
  definitions:
  - pkgs:
    - flecsalemm-deps+hdf5+caliper+doxygen+graphviz+trilinos+portage+paraview
  - compilers:
    - '%gcc@7.4.0'
    - '%gcc@8.3.0'
  - backends:
    - backend=mpi
    - backend=legion
  - mpi_providers:
    - mpich@3.2.1+slurm+verbs
    - openmpi@3.1.4 fabrics=auto
  specs:
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$backends]
    - [$^mpi_providers]
    exclude:
    - +paraview ^openmpi
  packages:
    all:
      target: [x86_64]
      version: []
      compiler: []
      buildable: true
      modules: {}
      providers: {}
      paths: {}
  view: false
