spack:
  definitions:
  - pkgs:
    - flecsalemm-deps+hdf5+caliper+doxygen+graphviz+trilinos+portage+paraview
  - compilers:
    - '%gcc@7.4.0'
    - '%gcc@8.3.0'
  - backends:
    - backend=mpi
  - mpi_providers:
    - mpich@3.2.1+slurm+verbs device=ch3
    - openmpi@3.1.4+pmi+legacylaunchers+thread_multiple fabrics=auto
  specs:
  - flecsi@2.1.0~external_cinch+hdf5%gcc@9.3.0 ^openmpi@4.1.0+pmi+legacylaunchers+thread_multiple fabrics=auto
  - flecsi@2.1.0~external_cinch+hdf5%gcc@9.3.0 ^mpich@3.4.1+slurm+verbs device=ch3
  - flecsi@2.1.0~external_cinch+hdf5 backend=legion%gcc@9.3.0 ^legion conduit=mpi ^openmpi@4.1.0+pmi+legacylaunchers+thread_multiple fabrics=auto
  - flecsi@2.1.0~external_cinch+hdf5 backend=legion%gcc@9.3.0 ^legion conduit=mpi ^mpich@3.4.1+slurm+verbs device=ch3
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$backends]
    - [$^mpi_providers]
    exclude:
    - +paraview ^openmpi
  packages:
    all:
      target: [x86_64]
      version: []
      compiler: []
      buildable: true
      providers: {}
  view: false
